In [5]:
import pandas as pd

import pandas as pd
import os


PATH = os.getcwd()
data_path = PATH +"/Polymer_lake/"

# Read the CSV file into a DataFrame
df = pd.read_csv(data_path+'Khazana.csv')

# Rename the 'smiles' column to 'PSMILES'
df.rename(columns={'smiles': 'PSMILES'}, inplace=True)

# Pivot the DataFrame to create a sparse matrix
sparse_matrix = df.pivot( index = 'PSMILES',columns=['property', ], values='value')


sparse_matrix.reset_index(inplace=True)
# Write the sparse matrix to a new CSV file
sparse_matrix.to_csv('Polymer_lake/KhazanaMatrix.csv',index=False)

In [6]:
sparse_matrix

property,PSMILES,Eat,Eea,Egb,Egc,Ei,Xc,eps,nc
0,C(=O)([*])C1=CC=C(C=C1)C(=O)OC1=CC=C(C=C1)C2(C...,NaN,NaN,NaN,3.8358,NaN,NaN,NaN,NaN
1,C(=O)([*])C1=CC=C(C=C1)S(=O)(=O)C1=CC=C(C=C1)C...,NaN,NaN,NaN,3.2146,NaN,NaN,NaN,NaN
2,C(=O)([*])C1=CC=C(C=C1)S(=O)(=O)C1=CC=C(C=C1)C...,NaN,NaN,NaN,3.3925,NaN,NaN,NaN,NaN
3,C13C(C=[*])OC(C=[*])C1C(=O)N(C2=CC=C(C(F)(F)F)...,NaN,NaN,NaN,5.3690,NaN,NaN,NaN,NaN
4,C13C(C=[*])OC(C=[*])C1C(=O)N(C2=CC=CC(C(F)(F)F...,NaN,NaN,NaN,5.0879,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3650,[*]c8ccc(C7(c4ccc(n3c(=O)c2cc1c(=O)n([*])c(=O)...,NaN,NaN,NaN,2.1924,NaN,NaN,NaN,NaN
3651,[*]c8ccc(C7(c5ccc(n4c(=O)c3ccc(Oc2ccc1c(=O)n([...,NaN,NaN,NaN,3.3847,NaN,NaN,NaN,NaN
3652,[*]c9ccc(C8(c5ccc(n4c(=O)c3ccc(C(=O)c2ccc1c(=O...,NaN,NaN,NaN,2.4589,NaN,NaN,NaN,NaN
3653,[*]n1nc(-n2c(=O)c3cc4c(=O)n([*])c(=O)c4cc3c2=O...,NaN,NaN,NaN,2.9967,NaN,NaN,NaN,NaN
3654,c1([*])cc(c2cc1)N=C(N2(C(c2(c3))=O))c1c2c(c4(c...,NaN,NaN,NaN,2.3866,NaN,NaN,NaN,NaN

In [9]:
df1 = pd.read_csv("/home/matt/Proj/MatSciCuration_TBV/PreCuration/Polymers/Polymer_lake/highTdata.csv")
df1 = df1.rename(columns = {"smis.uni":"PSMILES"})
df0 = pd.read_csv('Polymer_lake/KhazanaMatrix.csv')

In [10]:
df1 = df1.drop(['Unnamed: 0'],axis=1)

In [11]:
df0.reset_index(inplace=True)

In [12]:
DF = df0.merge(df1, on='PSMILES', how = 'outer')

In [13]:
DF.to_csv("/home/matt/Proj/MatSciCuration_TBV/PreCuration/Polymers/Polymer_lake/TandKhaz.csv",index = False)

# merge this data with the CROW data

In [14]:

import pandas as pd
import json

# Read the JSON file
with open('/home/matt/Proj/MatSciCuration_TBV/PreCuration/Polymers/Polymer_lake/CROW_PSMILES.json', 'r') as f:
    json_data = json.load(f)

In [15]:
# Convert the JSON data to a pandas DataFrame
json_df = pd.json_normalize(json_data)

In [16]:
json_df

,polymer name,NAMES AND IDENTIFIERS OF POLYMER,IDENTIFIERS OF MONOMER(S),Thermo-Physical Properties: Experimental / Literature Data,Thermo-Physical Properties: Calculated Data
0,Poly(acrylamide),"[{'POLYMER CLASS': 'Polyacrylamide'}, {'COMMON...","[{'CAS #': '79-06-1'}, {'COMMON NAMES': 'Acryl...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER..."
1,Poly(N-isopropyl acrylamide),"[{'POLYMER CLASS': 'Polyacrylamide'}, {'COMMON...","[{'CAS #': '2210-25-5'}, {'COMMON NAMES': 'N-I...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER..."
2,Poly(N-octyl acrylamide),"[{'POLYMER CLASS': 'Polyacrylamide'}, {'COMMON...","[{'CAS #': '10124-68-2'}, {'COMMON NAMES': ''}...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER..."
3,Poly(N-tert-butyl acrylamide),"[{'POLYMER CLASS': 'Polyacrylamide'}, {'COMMON...","[{'CAS #': '107-58-4'}, {'COMMON NAMES': 'N-te...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER..."
4,Poly(N-phenylacrylamide),"[{'POLYMER CLASS': 'Polyacrylamide'}, {'COMMON...","[{'CAS #': '2210-24-4'}, {'COMMON NAMES': 'N-P...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER..."
...,...,...,...,...,...
416,Poly(butyl vinyl thioether),"[{'POLYMER CLASS': 'Polyvinylsulfide'}, {'COMM...","[{'CAS #': '4789-70-2'}, {'COMMON NAMES': 'But...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER..."
417,Poly(ethyl vinyl thioether),"[{'POLYMER CLASS': 'Polyvinylsulfide'}, {'COMM...","[{'CAS #': '627-50-9'}, {'COMMON NAMES': 'Ethy...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER..."
418,Poly(methyl vinyl thioether),"[{'POLYMER CLASS': 'Polyvinylsulfide'}, {'COMM...","[{'CAS #': '1822-74-8'}, {'COMMON NAMES': 'Met...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER..."
419,Poly(vinyl phenyl sulfide),"[{'POLYMER CLASS': 'Polyvinylsulfide'}, {'COMM...","[{'CAS #': '1822-73-7'}, {'COMMON NAMES': 'Vin...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER..."
420,Poly(propyl vinyl thioether),"[{'POLYMER CLASS': 'Polyvinylsulfide'}, {'COMM...","[{'CAS #': '16330-21-5'}, {'COMMON NAMES': 'Pr...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER..."

In [17]:
json_df["NAMES AND IDENTIFIERS OF POLYMER"][0][5]['PSMILES']

'*CC*(C(=O)N)'

In [18]:
psmiles  = [json_df["NAMES AND IDENTIFIERS OF POLYMER"][i][5]['PSMILES'] for i in range(0,len(json_df))]

In [19]:
json_df['PSMILES'] = psmiles

In [20]:
# Merge the DataFrames on the 'SMILES' column
merged_df = json_df.merge(DF, on='PSMILES', how='outer')

In [22]:
merged_df

,polymer name,NAMES AND IDENTIFIERS OF POLYMER,IDENTIFIERS OF MONOMER(S),Thermo-Physical Properties: Experimental / Literature Data,Thermo-Physical Properties: Calculated Data,PSMILES,index,Eat,Eea,Egb,Egc,Ei,Xc,eps,nc
0,Poly(sebacic anhydride),"[{'POLYMER CLASS': 'Polyanhydrides'}, {'COMMON...","[{'CAS #': '123-99-9.108-24-7'}, {'COMMON NAME...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...",,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,*C(=CC=C1)N=C1C(=CC=C2)N=C2*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,*C(=NC1=C2)OC1=CC(O3)=C2N=C3C(C=C4)=CC=C4*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,*C(=O)C(=S)C(=O)O*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,*C(=O)C(=S)OC(=S)*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4923,Poly(ether ether sulfone),"[{'POLYMER CLASS': 'Polyethersulfone'}, {'COMM...","[{'CAS #': '122-95-2.80-07-9'}, {'COMMON NAMES...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...",c*1ccc(cc1)S(=O)(=O)c1ccc(cc1)Oc1ccc(cc1)O*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4924,Poly(phenylsulfone),"[{'POLYMER CLASS': 'Polyethersulfone'}, {'COMM...","[{'CAS #': '92-88-6.80-07-9'}, {'COMMON NAMES'...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...",c*1ccc(cc1)S(=O)(=O)c1ccc(cc1)Oc1ccc(cc1)c1ccc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4925,Poly(phenylsulfone),"[{'POLYMER CLASS': 'Polyethersulfone'}, {'COMM...","[{'CAS #': '92-88-6.80-07-9'}, {'COMMON NAMES'...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...",c*1ccc(cc1)S(=O)(=O)c1ccc(cc1)Oc1ccc(cc1)c1ccc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4926,Poly(phenylsulfone),"[{'POLYMER CLASS': 'Polyethersulfone'}, {'COMM...","[{'CAS #': '92-88-6.80-07-9'}, {'COMMON NAMES'...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...","[{'PROPERTY': 'UNIT', 'VALUE / RANGE': 'PREFER...",c*1ccc(cc1)S(=O)(=O)c1ccc(cc1)Oc1ccc(cc1)c1ccc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4927,NaN,NaN,NaN,NaN,NaN,c1([*])cc(c2cc1)N=C(N2(C(c2(c3))=O))c1c2c(c4(c...,3654.0,NaN,NaN,NaN,2.3866,NaN,NaN,NaN,NaN

In [21]:
merged_df.to_csv("PolymerData_uncurated.csv",index=False)